site_name: "AI Agent Documentation Center"  # 网站标题
nav:                          # 导航菜单
  - Home: index.md
  - Development Guide:
      - Environment Configuration: development/env.md
      - API Specifications: development/api.md
  - Deployment Manual: deployment.md

theme:
  name: material
  features:
    - navigation.tabs     # 顶部标签导航
    - search.highlight    # 搜索关键词高亮
  palette:               # 配色方案
    primary: deep purple
    accent: yellow

markdown_extensions:
  - admonition           # 提示块
  - toc:                 # 目录锚点
      permalink: true
  - pymdownx.superfences # 高级代码块

plugins:
  - search                    # 启用搜索功能

docs_dir: src
site_dir: docs
